# Generated by Django 5.0.6 on 2024-06-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('ISBN10', models.BigIntegerField()),
                ('Image', models.ImageField(upload_to='media')),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_Amount', models.FloatField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.book')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.customer')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
