# Generated by Django 5.0.6 on 2024-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('ISBN10', models.BigIntegerField()),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
