# Generated by Django 5.0.6 on 2024-06-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystemApp', '0002_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(max_length=100)),
                ('Order_Date', models.DateField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.BigIntegerField()),
                ('Order_Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Status', models.CharField(default='Pending', max_length=100)),
                ('Transaction_ID', models.CharField(max_length=200)),
                ('Payment_Mode', models.CharField(default='PayU', max_length=100)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.customer')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.order')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.book')),
                ('Payment_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementSystemApp.payment')),
            ],
            options={
                'db_table': 'OrderDetail',
            },
        ),
    ]
